import Head from 'next/head'
import {CandidateBar, useCloseButton} from '../components/Candidates'
import styles from '../../styles/Home.module.css'
import {useCandidates} from "../services";
import QuestionSection from "../components/Question";


export default function Home() {
    const {currCandidateIndex, currCandidate, changeCurrCandidate, candidates, currApplication} =  useCandidates();
    const [closeButton, open] = useCloseButton()

  return (
    <div className={styles.container}>
      <Head>
        <title>Interviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CandidateBar candidateList={candidates} currCandidateIndex = {currCandidateIndex} changeCurrCandidate = {changeCurrCandidate} open={open}/>
            {closeButton}
          <QuestionSection currCandidate={currCandidate} currApplication={currApplication}/>
      </main>
    </div>
  )
}
